eg012EmbeddedConsole implemented
NicklausBrain/code-examples-powershell pull request #7
Opened 2020-09-21 16:22 UTC by NicklausBrain

2020-09-21 16:25 UTC, NicklausBrain commented
@serhio17 I must confess that even though API successfully returned the console URL, it opens the empty page

`The console URL is https://demo.docusign.net/Member/StartInSession.aspx?StartConsole=1&t=cb9fb0c5-2b93-47bc-8b79-c6d789cd2eac`

Please test the sample yourself as well, it is interesting what will you get.

2020-09-21 21:50 UTC, serhio17 commented
The URL https://demo.docusign.net/Member/StartInSession.aspx?StartConsole=1&t=cb9fb0c5-2b93-47bc-8b79-c6d789cd2eac redirects me to the login page where I have to login to my docusign account...

2020-09-22 07:29 UTC, serhio17 requested changes
The rest looks good

2020-09-22 07:29 UTC, serhio17 commented on examples/eg012EmbeddedConsole.ps1
> +$response = New-TemporaryFile
The "$response" variable is not used in the script. Need to remove it

2020-09-22 10:48 UTC, merged